version: '3.9'

services:
  dstproject-application:
    image: leozin89/dstproject-application:v5
    environment:
      - DB=your_db
      - USER_DB=user_db
      - PASSWORD_DB=your_password_db
    ports:
      - 8762:8762
    networks:
      - distnetworkcluster
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure

  visualizer:
    image: dockersamples/visualizer
    ports:
      - 8080:8080
    networks:
      - distnetworkcluster
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  distnetworkcluster:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.238.0/24
       

          
   
