 pipeline {
    agent any 

    //read the doc: https://www.jenkins.io/doc/book/pipeline/docker/
    stages {
     
        stage('Build Image') {
            steps {
                script {
                    dockerapp = docker.build("docker_username/docker_repo:${env.BUILD_ID}")
                }
            }
        }

        //dockerhub** reference a credentials ENV saved in manager credentials in jenkins
        stage('push Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub'){
                        dockerapp.push("latest")
                        dockerapp.push("${env.BUILD_ID}")
                     }
                }
            }
        }

        stage('Deploy Container Image on Server') {
            steps {
                   sh 'docker run -d -p 8766:8766 --name app -e PROD_CLIENT=your_prod_client_db -e PROD_HOST=your_prod_host_db -e PROD_DB=your_prod_db -e PROD_USER_DB=your_prod_user_db -e PROD_PASSWORD_DB=your_prod_password_db leozin89/dist-node-api:latest'
            }
        }

        
    }

}
 
